config/routes.rb
Rails.application.routes.draw do
  resources :user_events
  resources :gifts
  resources :swaps
  resources :events
  resources :users

  get '/signup', to: 'users#new', as: 'signup'
  # get '/dashboard', to: 'users#show', as: 'user_dashboard'
  #   resources :users
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/', to: 'static#home', as: 'home_path'

  root to: 'static#home'
  resources :categories

end

app/models/user.rb
class User < ApplicationRecord
  
  has_secure_password
  
  has_many :user_events
  has_many :events, through: :user_events
  has_many :swaps_received, class_name: 'Swap', foreign_key: 'giver_id'
  has_many :swaps_given, class_name: 'Swap', foreign_key: 'receiver_id'
  has_many :gifts, through: :swaps

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_email_format_of :email, :message => 'is not a valid email.'
  validates :password_digest, length: {minimum: 8}

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  # def category_preferences
  #   @category_preferences = ["#{self.cat_1}", "#{self.cat_2}", "#{self.cat_3}"]
  # end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :set_user, only: [:show, :edit, :destroy]

  def new
    @user = User.new
  end

  def create
    # byebug
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:notice] = "That is not a valid user."  # can i iterate through error messages and display each one as a flash notice?
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user = User.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

private

  # def set_user
  #   @user = User.find(params[:id])
  # end


  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :bio, :cat_1, :cat_2, :cat_3)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>Edit User</h2>

<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :password_digest %>
  <%= f.text_field :password_digest %>
  <br>
  <%= f.submit "Edit User" %>
<% end %>

app/views/users/new.html.erb
<h2>Create a New User</h2>

<%= form_for @user do |f| %>
  <%= f.label :first_name, 'First Name' %>
  <%= f.text_field :first_name %>
  <br>
  <%= f.label :last_name, 'Last Name' %>
  <%= f.text_field :last_name %>
  <br>
  <%= f.label :email, 'Email' %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :password, 'Password' %>
  <%= f.text_field :password %>
  <br>
  <%= f.label :bio, 'Tell us about yourself:' %>
  <%= f.text_area :bio %>
  <br>
  <%= f.label :cat_1, 'Preferred Gift Category' %>
  <%= f.text_field :cat_1 %>
  <br>
  <%= f.label :cat_2, 'Preferred Gift Category' %>
  <%= f.text_field :cat_2 %>
  <br>
  <%= f.label :cat_3, 'Preferred Gift Category' %>
  <%= f.text_field :cat_3 %>
  <br>
  <%= f.submit "Create User" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.full_name %><h1>

<h2>Gift Preferences</h2>
    <ul>
        <li><%= @user.cat_1 %></li>
        <li><%= @user.cat_2 %></li>
        <li><%= @user.cat_3 %></li>
    </ul>

<h2>Events</h2>

  <p><%= link_to "Create New Event", new_event_path %></p>

    <p><%= @user.events.each do |event| %></p>
        <strong><%= event.title %></strong><br>
        Date: <%= event.date %><br>
        Location: <%= event.location %><br>
        Occasion: <%= event.occasion %><br>
        Spending Limit: $<%= event.spending_limit %></p>
        Give a gift to: [add swap-receiver association here<%= %>]
    <% end %>


<h2>Gifts Given</h2>




<h2>Gifts Received</h2>