config/routes.rb
Rails.application.routes.draw do
  resources :user_events
  resources :gifts
  resources :swaps
  resources :events
  resources :users

  get '/signup', to: 'users#new', as: 'signup'
  # get '/dashboard', to: 'users#show', as: 'user_dashboard'
  #   resources :users
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/', to: 'static#home', as: 'home_path'

  root to: 'static#home'
  resources :categories

end

app/models/event.rb
class Event < ApplicationRecord
  has_many :user_events
  has_many :users, through: :user_events
  has_many :swaps
  has_many :gifts, through: :swaps


  def receivers
    self.users
  end

  def givers
    self.users
  end

  # def receivers
  #   @receiver = self.user.shuffle!
  # end
  #
  # def givers
  #   @giver = self.user
  # end

  # def generate_swap
  #   pairs = (self.users.map{|x| x.id}).zip(self.users.shuffle.map{|x| x.id})
  #   pairs.each do |pair|
  #   if pair[0] != pair[1]
  #    Swap.create(giver_id: pair[0], receiver_id: pair[1], gift_id: nil, event_id: self.id)
  #  else
  #   end
  #
  # end

#   def generate_pairs
#     givers = self.users
#     receivers = self.users
#     answer = {}
#     until answer.keys.count == givers.length && !answer.values.include?(nil)
#       givers.each do |giver|
#           receiver = receivers.sample
#         unless receiver == giver
#         answer[giver] = receiver
#         receivers.delete(receiver)
#       end
#     end
#   end
#   answer
# end

def generate_pairs
  peeps = self.users.shuffle
  holder = {}
  peeps.each_with_index {|person, index|
    holder[person] = peeps[index+1]}
    holder[holder.keys.last] = peeps[0]
    holder
end

def generate_swap
  pairs = generate_pairs
  pairs.each do |giver, receiver|
    Swap.new(giver: giver, receiver: receiver, gift_id: nil, event_id: self)
  end
  "Swaps created! Check you dashboard to see who you'll be giving a gift to!"
end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user, only: [:index, :new, :show, :edit, :update, :destroy]


  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.users
    @swaps = @event.generate_pairs
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.save
    redirect_to event_path(@event)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.update(event_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :date, :spending_limit, :location, :occasion)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<h1>Edit @event.title</h1>

<%= form_for @event do |f| %>
<%= f.label :title %>
<%= f.text_field :title %><br><br>

<%= f.label :date %>
<%= f.datetime_select :date, :ampm => true, :minute_step => 15 %><br><br>

<%= f.label :spending_limit %>
<%= f.text_field :spending_limit %><br><br>

<%= f.label :location %>
<%= f.text_field :location %><br><br>

<%= f.label :occasion %>
<%= f.text_field :occasion %><br><br>

<%= f.submit "Edit Your Event" %><br><br>
<% end %>

app/views/events/index.html.erb
<h1>All Events</h1>

<ul>
  <% @events.each do |event| %>
    <li>
      <%= link_to event.title, event_path(event) %>
    </li>
    <% end %>
  </ul>

app/views/events/new.html.erb
<h1>Create a New Event!</h1>

<%= form_for @event do |f| %>
<%= f.label :title %>
<%= f.text_field :title %><br><br>

<%= f.label :date %>
<%= f.datetime_select :date, :start_year=>2017,:end_year=>2019, :ampm => true, :minute_step => 15 %><br><br>

<%= f.label :spending_limit %>
<%= f.text_field :spending_limit %><br><br>

<%= f.label :location %>
<%= f.text_field :location %><br><br>

<%= f.label :occasion %>
<%= f.text_field :occasion %><br><br>

<%= f.submit "Create Your Event" %><br><br>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<h2>You're Invited! </h2>

<ul>
  <li><b>What?</b> <%= @event.occasion %></liu>
  <li><b>When?</b> <%= @event.date.strftime("%B %d, %Y") %> at <%= @event.date.strftime("%I:%M %p") %></liu>
  <li><b>Where?</b> <%= @event.location %></liu>
  <li><b>How Much?</b> $<%= @event.spending_limit %> spending limit</li>
</ul>

<h3>Attendees</h3>
<ul>
  <% @attendees.each do |att| %>
    <li> <%= att.first_name %> </li>
    <% end %>
</ul>

<h3>Matches</h3>
<ul>
  <% @swaps.each do |giv, rec| %>
    <li> <%= giv %> = <%= rec %></li>
    <% end %>
</ul>


<%= form_for :user_events, url: user_events_path do |f| %>
	<%= f.label :user, for: :user_id %>
	<%= f.collection_select :user_id, User.all, :id, :first_name %>
	<%= f.hidden_field :event_id, value: @event.id %>
  <%= f.hidden_field :path_name, value: "/events/#{@event.id}" %>
  <%= f.hidden_field :user_id, value: "#{@user.id}" %
	<%= f.submit "Add user" %>
<% end %>


<h5><%= link_to("Create Swaps", event_path(@event), class: "button-alt")%></h5>
<h5><%= link_to("Delete Event", event_path, method: :delete, class: "delete_button")%></h5>